/*
 * Copyright 2014 Tilera Corporation. All Rights Reserved.
 *
 *   The source code contained or described herein and all documents
 *   related to the source code ("Material") are owned by Tilera
 *   Corporation or its suppliers or licensors.  Title to the Material
 *   remains with Tilera Corporation or its suppliers and licensors. The
 *   software is licensed under the Tilera MDE License.
 *
 *   Unless otherwise agreed by Tilera in writing, you may not remove or
 *   alter this notice or any other notice embedded in Materials by Tilera
 *   or Tilera's suppliers or licensors in any way.
 */

/**
 * @file
 *
 * Support code and defines for the assembly-file header generator.
 */

#include <stdarg.h>
#include <stdint.h>
#include <string.h>

#include <arch/chip.h>
#include <arch/sim.h>

/*
 * This header file provides a set of macros which can be used
 * to convert definitions and type declarations in C header files
 * (called _source_definitions_) into definitions suitable for use in
 * assembly-language programs (called _output_definitions_).  They are
 * normally used as follows:
 *
 * - You write a C source file which includes this header file and
 *   some other header files whose definitions and types you need in
 *   your assembly code.  That C file then contains calls to the macros
 *   which reference the specific source definitions or type fields which
 *   you need.
 *
 * - You compile that C program with tile-cc, and then run it under
 *   tile-sim.  The program then produces, on its standard output,
 *   a header file which contains the output definitions, which can be
 *   included in an assembly program.
 *
 * Obviously, in order to stay synchronized with changes to the original
 * header files, you want to do the output header generation as part of
 * building your assembly program, not as a one-time event.  The tile-sim
 * run takes negligible time, so it's quite reasonable to automate this
 * via Makefile rules.
 *
 * Macro usage:
 *
 * ASMHDR_BEGIN()
 *
 *   This macro is included exactly once in your C source file, after
 *   you've included any necessary header files and before any other macros
 *   are invoked.
 *
 * ASMHDR_DEF(name)
 *
 *   This macro is used to incorporate single source definitions.
 *   These may be either #defines, or enum values.  name is the name
 *   both of the value retrieved from the source header files, and of
 *   the output definition.  If the source definition is a #define,
 *   it must evaluate to a numeric value.
 *
 *   One output definition is always produced by this macro:
 *
 *   <name>         the value
 *
 *   If the value is a power of two, an additional output definition
 *   is produced:
 *
 *   <name>_SHIFT   log2(value), or the number of bits by which you would
 *                  have to left-shift a 1 to produce the value.
 *
 * ASMHDR_TYPE(name, prefix)
 *
 *   This macro starts a sequence of ASMHDR_MEMBER or ASMHDR_BITFIELD calls
 *   which are made in the context of a specific struct or union type.
 *   name is the name of that type, and prefix is a string which, along
 *   with a trailing undercore, will be prepended to all of the output
 *   definitions associated with that type.  If prefix is omitted, the
 *   prefix used will be the name itself, converted to uppercase.
 *
 * ASMHDR_MEMBER(name, outname)
 *
 *   This macro extracts the offset and size of a particular member within
 *   the currently active structure or union.  name is the name of the
 *   member; note that it's legal to have a multi-component name, like
 *   foo.bar, to reference something which might be enclosed in multiple
 *   levels of structs; array references are also legal.  outname is
 *   the base name for the output definitions; if not supplied, name
 *   will be used, converted to uppercase and with any non-alphanumeric
 *   non-underscore characters replaced with an underscore.
 *
 *   Two output definitions are generated by this macro:
 *
 *   <prefix>_<name>_OFF    the byte offset of the member within the
 *                          structure
 *
 *   <prefix>_<name>_SIZE   the size in bytes of the member
 *
 * ASMHDR_BITFIELD(name, outname)
 *
 *   This macro extracts the offset and size of a particular member
 *   within the currently active structure or union.  name is the name
 *   of the member.  (Note that it's legal to have a multi-component
 *   name, like foo.bar, to reference something which might be enclosed
 *   in multiple levels of structs; array references are also legal.)
 *   outname is the base name for the output definitions; if not supplied,
 *   name will be used, converted to uppercase and with any non-alphanumeric
 *   non-underscore characters replaced with an underscore.
 *
 *   Five output definitions are generated by this macro:
 *
 *   <prefix>_<name>_OFF   the byte offset of the word within the structure
 *                         that contains the bitfield
 *
 *   <prefix>_<name>_SHIFT the number of bits you'd have to right-shift that
 *                         enclosing word to bring the bitfield down to the
 *                         least significant bits of the word
 *
 *   <prefix>_<name>_WIDTH the width of the bitfield in bits
 *
 *   <prefix>_<name>_MASK  a mask of 1 bits equal in size and alignment to
 *                         the bits of the bitfield
 *
 *   <prefix>_<name>_RMASK a mask of 1 bits equal in size to the bitfield,
 *                         but shifted right so that it resides in the least
 *                         significant bits of the word
 *
 * ASMHDR_ENDTYPE()
 *
 *   This macro is included once for every invocation of ASMHDR_TYPE,
 *   and occurs after that invocation and all dependent invocations of
 *   ASMHDR_MEMBER or ASMHDR_BITFIELD.
 *
 * ASMHDR_OUT(string)
 *
 *   This macro emits the given argument string (which must be enclosed
 *   in double quotes) to the output file, followed by a newline.
 *   Normally you will not need to use this, but it might be handy if you
 *   need to construct a value based on definitions produced by previous
 *   macro invocations.
 *
 * ASMHDR_END()
 *
 *   This macro is included exactly once in your C source file, as the
 *   very last macro invocation.
 */

#ifndef __DOXYGEN__

#ifdef NATIVE

#include <stdio.h>
#define rputc putchar
#define rputs(s) fputs(s, stdout)
#define rprintf printf

#else

static void
rputc(char c)
{
  uint32_t val = SIM_CONTROL_PUTC | (c << _SIM_CONTROL_OPERATOR_BITS);
  __insn_mtspr(SPR_SIM_CONTROL, val);
}


static void
rputs(const char* string)
{
  for (int i = 0; string[i] != 0; i++)
    rputc(string[i]);
}


// Super stripped down printf. Only accepts %s, %X, %u and %%.
static void __attribute__((format(printf, 1, 2)))
rprintf(const char* fmt, ...)
{
  va_list ap;
  va_start(ap, fmt);

  const char* p = fmt;
  char c;
  while ((c = *p++) != '\0')
  {
    if (c != '%')
    {
      rputc(c);
      continue;
    }

    int ells = 0;

    while (*p == 'l')
    {
      ells++;
      p++;
    }

    switch (*p++)
    {
    case '%':
      rputc('%');
      break;
    case 's':
      rputs(va_arg(ap, char*));
      break;
    case 'X':
      {
        unsigned long n;
        if (ells)
          n = va_arg(ap, unsigned long);
        else
          n = va_arg(ap, unsigned int);

        if (n == 0)
        {
          rputc('0');
        }
        else
        {
          for (int i = 60 - (__insn_clz(n) & -4); i >= 0; i -= 4)
            rputc("0123456789ABCDEF"[(n >> i) & 0xF]);
        }
      }
      break;
    case 'u':
      {
        // Very rough implementation that works for the small
        // numbers we expect.
        unsigned int n = va_arg(ap, unsigned int);

        char buf[100];
        char* p = buf;

        do
        {
          *p++ = '0' + (n % 10);
          n /= 10;
        }
        while (n != 0);

        while (p > buf)
          rputc(*--p);
      }
      break;
    default:
      rputs("\n#error invalid format string: ");
      rputs(fmt);
      rputs("\n");
      return;
    }
  }
}

#endif

void
_asmhdr_do_def(char* name, unsigned long value)
{
  rprintf("#define %s 0x%lX\n", name, value);
  if (__insn_pcnt(value) == 1)
    rprintf("#define %s_SHIFT %u\n", name, (unsigned int) __insn_ctz(value));
  rputc('\n');
}

void
_asmhdr_do_bitfield(void *ptr, int size, char *prefix, char *name)
{
  if (((intptr_t) ptr & 3) || (size & 3))
  {
    //
    // We don't handle non-word-aligned structures yet.
    //
    rputs("#error Bitfield in non-word-aligned structure\n");
    return;
  }

  uint32_t *p = (uint32_t*) ptr;
  int nwds = size >> 2;

  int num_wds_nonzero = 0;
  for (int i = 0; i < nwds; i++)
    num_wds_nonzero += (p[i] != 0);

  if (num_wds_nonzero == 1)
  {
    for (int i = 0; i < nwds; i++)
    {
      if (p[i] != 0)
      {
        rprintf("#define %s_%s_OFF 0x%X\n", prefix, name, i << 2);
        rprintf("#define %s_%s_SHIFT %u\n", prefix, name,
                (unsigned int) __insn_ctz(p[i]));
        rprintf("#define %s_%s_WIDTH %u\n", prefix, name,
                (unsigned int) __insn_pcnt(p[i]));
        rprintf("#define %s_%s_MASK 0x%X\n", prefix, name, p[i]);
        rprintf("#define %s_%s_RMASK 0x%X\n", prefix, name,
               p[i] >> __insn_ctz(p[i]) );
        rputs("\n");
        return;
      }
    }
  }

  rputs("#error Bitfield crosses word boundary\n");
}


char*
_asmhdr_cleanupname(char* name, char* out)
{
  // Avoid using libc here, even though it would be handy.
  char* const ret = out;
  char c;

  for (char* in = name; (c = *in) != '\0'; in++)
  {
    if (c >= 'a' && c <= 'z')
      c += 'A' - 'a';
    else if ((c < '0' || c > '9') && (c < 'A' || c > 'Z') && c != '_')
      c = '_';
    *out++ = c;
  }
  *out = '\0';

  return ret;
}


#define _asmhdr_outname(name, outname, buf) \
  (outname[0] ? outname : _asmhdr_cleanupname(name, buf))


#ifdef NATIVE

#define ASMHDR_BEGIN() \
int \
main(int argc, char** argv) \
{ \
  rputs("/* This file is automatically generated.  DO NOT EDIT. */\n\n");

#else

#define ASMHDR_BEGIN() \
void \
_start(void) \
{ \
  rputs("/* This file is automatically generated.  DO NOT EDIT. */\n\n");

#endif

#define ASMHDR_DEF(name) \
  _asmhdr_do_def(#name, name);

#define ASMHDR_TYPE(name, prefix) \
  { \
    name _asmhdr_type; \
    char* _asmhdr_name = #name; \
    char _asmhdr_name_buf[sizeof(#name)]; \
    char* _asmhdr_prefix = _asmhdr_outname(_asmhdr_name, #prefix, \
                                           _asmhdr_name_buf); \
    rprintf("#define %s_SIZE 0x%X\n", _asmhdr_prefix, \
           (unsigned int) sizeof (_asmhdr_type)); \
    rputc('\n'); 

#define ASMHDR_MEMBER(name, outname) \
    { \
      char _asmhdr_memname_buf[sizeof(#name)]; \
      char* _asmhdr_memname = _asmhdr_outname(#name, #outname, \
                                              _asmhdr_memname_buf); \
      rprintf("/* Type %s, member %s */\n", _asmhdr_name, #name); \
      rprintf("#define %s_%s_OFF 0x%X\n", _asmhdr_prefix, _asmhdr_memname, \
             (unsigned int) ((intptr_t) &_asmhdr_type.name - \
                             (intptr_t) &_asmhdr_type)); \
      rprintf("#define %s_%s_SIZE 0x%X\n", _asmhdr_prefix, _asmhdr_memname, \
             (unsigned int) sizeof (_asmhdr_type.name)); \
      rputc('\n'); \
    }

#define ASMHDR_BITFIELD(name, outname) \
  { \
    char _asmhdr_bitfield_buf[sizeof(#name)]; \
    rprintf("/* Type %s, bitfield %s */\n", _asmhdr_name, #name); \
    memset(&_asmhdr_type, 0, sizeof(_asmhdr_type)); \
    _asmhdr_type.name = ~_asmhdr_type.name; \
    _asmhdr_do_bitfield(&_asmhdr_type, sizeof (_asmhdr_type), \
                        _asmhdr_prefix, _asmhdr_outname(#name, #outname, \
                        _asmhdr_bitfield_buf)); \
  }

#define ASMHDR_ENDTYPE() \
  }

#define ASMHDR_OUT(str) \
  rputs(str "\n");

#ifdef NATIVE
#define ASMHDR_END() \
}

#else

#define ASMHDR_END() \
  __insn_mtspr(SPR_SIM_CONTROL, SIM_CONTROL_PUTC | \
               (SIM_PUTC_FLUSH_BINARY << _SIM_CONTROL_OPERATOR_BITS)); \
  __insn_mtspr(SPR_SIM_CONTROL, SIM_CONTROL_SHUTDOWN); \
}

#endif

#endif /* !__DOXYGEN__ */
