/*
 * Copyright 2014 Tilera Corporation. All Rights Reserved.
 *
 *   The source code contained or described herein and all documents
 *   related to the source code ("Material") are owned by Tilera
 *   Corporation or its suppliers or licensors.  Title to the Material
 *   remains with Tilera Corporation or its suppliers and licensors. The
 *   software is licensed under the Tilera MDE License.
 *
 *   Unless otherwise agreed by Tilera in writing, you may not remove or
 *   alter this notice or any other notice embedded in Materials by Tilera
 *   or Tilera's suppliers or licensors in any way.
 */

/**
 * @file
 * Support for run-time patching of assembly code.
 */

#ifndef _SYS_HV_TILEGX_PATCH_H
#define _SYS_HV_TILEGX_PATCH_H

#ifndef __ASSEMBLER__

#include <arch/opcode.h>

/** Entry in a patch table, which describes one patch to be made to the
 *  hypervisor's code.
 */
struct patch_table_entry
{
  /** Pointer to the first instruction of the original code. */
  tilegx_bundle_bits* unpatched_code;
  /** Pointer to the first instruction of the code that will be added to,
   *  or which will replace, the original code. */
  tilegx_bundle_bits* patch_code;
  /** Patch mode (PATCH_MODE_XXX). */
  uint16_t patch_mode;
  /** Number of bundles replaced by the patch. */
  uint16_t replaced_bundles;
  /** Number of bundles in the replacement or inserted code. */
  uint16_t patch_bundles;
};

#endif

//
// Values for patch_mode.
//
/** Replace the original code with the patched code. */
#define PATCH_MODE_REPLACE        0
/** Execute the patched code before the following bundle, iff that bundle
 *  is executed. */
#define PATCH_MODE_INSERT_BEFORE  1
/** Execute the patched code after the preceding bundle, iff that bundle
 *  is executed. */
#define PATCH_MODE_INSERT_AFTER   2

#ifdef __ASSEMBLER__

#ifndef __DOXYGEN__

//
// Macros for patching assembly code at runtime.
//
//   These macros support writing assembly code which has predefined
//   patches: either replacement of code, or insertion of new code.  These
//   patches can be enabled at runtime if desired; if they aren't enabled,
//   there's no performance penalty for the original code.  This is helpful
//   when implementing things like tracing of time-critical interrupt
//   routines.
//
//   To do code replacement with a patch, you do:
//
//     patch_replace NAME
//     // Original code, to be replaced by the patch, goes here
//     patch_with
//     // Patch code, to replace the code above when the patch is enabled,
//     // goes here
//     patch_end
//
//   (NAME here and below is an identifier that distinguishes different
//   sets of patches.  Each identifier must be registered with the
//   patch_init macro and closed out with the patch_fini macro.)
//
//   To do code insertion with a patch, you do either:
//
//     patch_insert_before NAME
//     // Patch code, to run before the next bundle when the patch is
//     // enabled, goes here
//     patch_end
//
//   or:
//   
//     patch_insert_after NAME
//     // Patch code, to run after the previous bundle when the patch is
//     // enabled, goes here
//     patch_end
//
//   In most repects, the two flavors of patch_insert behave identically.
//   The difference is what happens when the bundle which is the target of
//   the insertion is skipped over by a control transfer.  For instance,
//   consider this code:
//
//     bnez     r1, 0f
//     addli    r0, 0x1234
//   0:
//     patch_insert_XXX NAME
//     // patch code
//     patch_end
//     movei    r2, 0x2345
//
//   If you use patch_insert_after here, then the patch code executes if,
//   and only if, the addli executes.  If the bnez skips the addli, the
//   patch code will not run.  That may be what you want, and if so, you
//   should probably make that intention clear by moving the 0: label
//   after the patch_end statement.  However, if you wanted the patch
//   code to always execute, as most readers would expect, then you
//   need to use patch_insert_before, which will run the patch if and
//   only if the movei executes.
//

//
// Macro Implementation Notes
//
//   We need to maintain common state (a couple of addresses) between
//   matching pairs/triples of macros; e.g., patch_end needs access to
//   values computed by patch_replace and patch_with.  We can't just
//   assign these values to ordinary symbols, since symbols are resolved
//   not at assembly time, but at link time.  In other words, if every
//   patch_replace assigned to symbol X, then the code generated by every
//   patch_end would get the same value for X, not the value set by the
//   immediately preceding patch_replace.
//
//   To fix this, we can generate unique symbols for each invocation of a
//   patch macro, using the \@ unique counter supplied by the assembler to
//   each macro.  So, the first invocation of patch_replace might assign
//   to X1, while the next one assigns to X5.  However, we still have the
//   problem of providing the matching macro or macros with access to
//   those symbols; we can't set a symbol to a symbol name and indirectly
//   reference it, for instance.
//
//   The way to make that work is kind of a neat hack.  The first macro
//   in a pair/triple uses \@ to generate unique names for all of them
//   symbols it defines.  Then, it generates custom versions of the other
//   macro or macros in the set, where it wires in that value of \@ to
//   the macro itself; those macros thus refer to the same
//   invocation-unique symbols that the first one did.  When the macro
//   has executed, it purges itself, so it can be recreated for the
//   next use.
//
//   This has the nice property that we don't need to define separate
//   patch_end_XXX macros for the three separate cases; it just gets
//   defined to do the right thing based on the macro it follows, so the
//   code looks cleaner and is easier to understand.  Another benefit is
//   that it's impossible to use the macros out of sequence; you can't call
//   patch_with before patch_replace, or more than once, because it doesn't
//   exist until patch_replace is called, and then it deletes itself once
//   it's been used once.
//

        //
        // Set up data structures for a new patch set.  This needs to be
        // assembled before any calls to any other patch_ macros.
        //
        // @param name Identifier for the patch set.
        //
	.macro	patch_init name:req

        // Start the patch table.
	.pushsection .data.patch_table_\name, "a"
	.global patch_table_\name
	.align  8
patch_table_\name:
	.popsection

        // Start the patch code area.
	.pushsection .text.patch_code_\name, "ax"
	.align  8
	.popsection

	.endm


        //
        // Close out data structures for a patch set.  This needs to be
        // assembled after all calls to any other patch_ macros.
        //
        // @param name Identifier for the patch set.
        //
	.macro	patch_fini name:req

	// Terminate the patch table.
	.pushsection .data.patch_table_\name
	.quad	0, 0, 0
        .size   patch_table_\name, . - patch_table_\name
	.popsection

	.endm


        //
        // Start a sequence of code that will be replaced by a patch.  Must
        // be followed by patch_with, which starts the code that is used
        // instead when the patch is activated, and then patch_end, which
        // ends the substituted code.
        //
        // @param name Identifier for the patch set.
        //
	.macro	patch_replace name:req

        // Remember where the code to be replaced starts.
	.L_patch_replace_start_\name&_\@ = .

        // Define the temporary version of patch_with which corresponds
        // to this patch_replace invocation.
        .macro patch_with
        _patch_with \name \@
        .endm

	.endm

        // Actual implementation of patch_with; not called directly.
	.macro	_patch_with name:req key:req

        // Remember where the code to be replaced ends (actually, the
        // bundle past that code).
	.L_patch_replace_end_\name&_\key = .

        // Prepare to assemble the patch into a different section.
	.pushsection .text.patch_code_\name, "ax"
        // Remember where the patch code starts.
	_patch_code_start_\name&_\key = .

        // Get rid of the temporary macro which called us.
        .purgem patch_with

        // Define the temporary version of patch_end which corresponds
        // to this patch_replace invocation.
        .macro patch_end
        _patch_replace_end \name \key
        .endm

	.endm


        //
        // Actual implementation of patch_end after patch_replace/patch_with.
        // Not called directly.
        //
	.macro	_patch_replace_end name:req key:req

        // Remember where the patch code ends.
	.L_patch_code_end_\name&_\key = .
        // When we finish executing the patch, we jump to the bundle after
        // the replaced code.
	j	.L_patch_replace_end_\name&_\key
	.size   _patch_code_start_\name&_\key, . - _patch_code_start_\name&_\key
	.popsection

        // Make an entry in the patch table.
	.pushsection .data.patch_table_\name
	// Start of code to be replaced.
	.quad	.L_patch_replace_start_\name&_\key
	// Start of code to use instead.
	.quad	 _patch_code_start_\name&_\key
	// Patch mode.
	.hword	PATCH_MODE_REPLACE
	// Number of bundles of code to be replaced.
	.hword	(.L_patch_replace_end_\name&_\key - \
                 .L_patch_replace_start_\name&_\key) / BUNDLE_SIZE
	// Number of bundles of code to be used instead.
	.hword	(.L_patch_code_end_\name&_\key - \
                 _patch_code_start_\name&_\key) / BUNDLE_SIZE
	.align 8
	.popsection

        // Get rid of the temporary macro which called us.
        .purgem patch_end

        .endm


        //
        // Start a sequence of patch code that will be inserted before the
        // following bundle; i.e., it will execute before that bundle, iff
        // that bundle executes.  Must be followed by patch_end, which
        // ends the inserted code.
        //
        // @param name Identifier for the patch set.
        //
	.macro	patch_insert_before name:req

        // Remember the address of the bundle we're inserting before.
	.L_patch_insert_at_\name&_\@ = .

        // Prepare to assemble the patch into a different section.
	.pushsection .text.patch_code_\name
        // Remember where the patch code starts.
	_patch_code_start_\name&_\@ = .

        // Define the temporary version of patch_end which corresponds
        // to this patch_insert_before invocation.
        .macro patch_end
        _patch_insert_before_end \name \@
        .endm

	.endm

        //
        // Actual implementation of patch_end after patch_insert_before.
        // Not called directly.
        //
	.macro	_patch_insert_before_end name:req key:req

        // Remember where the patch code ends.
	.L_patch_code_end_\name&_\key = .
	// This NOP will be replaced with the instruction just before
	// __patch_insert_at_\name.
        nop
        // Jump to the bundle after the bundle we inserted before.
	j       .L_patch_insert_at_\name&_\key + BUNDLE_SIZE
	.size   _patch_code_start_\name&_\key, . - _patch_code_start_\name&_\key
	.popsection

        // Make an entry in the patch table.
	.pushsection .data.patch_table_\name
	// Bundle that will be moved to _patch_code_end, then replaced
	// with a jump to that location.
	.quad   .L_patch_insert_at_\name&_\key
	// Where the inserted code is located.
	.quad   _patch_code_start_\name&_\key
	// Patch mode.
	.hword  PATCH_MODE_INSERT_BEFORE
	// Unused (no code being replaced).
	.hword	0
	// Number of bundles of code to be inserted; this does not count
        // the nop which will be replaced by the original instruction at
        // the insertion point, nor the jump that follows it.
	.hword	(.L_patch_code_end_\name&_\key - \
                 _patch_code_start_\name&_\key) / BUNDLE_SIZE
	// End of entry.
	.align  8
	.popsection

        // Get rid of the temporary macro which called us.
        .purgem patch_end

	.endm


        //
        // Start a sequence of patch code that will be inserted after the
        // preceding bundle; i.e., it will execute before that bundle, iff
        // that bundle executes.  Must be followed by patch_end, which
        // ends the inserted code.
        //
        // @param name Identifier for the patch set.
        //
	.macro	patch_insert_after name:req

        // Remember the address of the bundle we're inserting after.
	.L_patch_insert_at_\name&_\@ = . - BUNDLE_SIZE

	.pushsection .text.patch_code_\name
	_patch_code_start_\name&_\@ = .
	// This NOP will be replaced with the instruction at
	// __patch_insert_at_\name.
	nop

        // Define the temporary version of patch_end which corresponds
        // to this patch_insert_after invocation.
        .macro patch_end
        _patch_insert_after_end \name \@
        .endm

	.endm

        //
        // Actual implementation of patch_end after patch_insert_after.
        // Not called directly.
        //
	.macro	_patch_insert_after_end name:req key:req

        // Remember where the patch code ends.
	.L_patch_code_end_\name&_\key = .
        // Jump to the bundle after the bundle we inserted after.
	j       .L_patch_insert_at_\name&_\key + BUNDLE_SIZE
	.size   _patch_code_start_\name&_\key, . - _patch_code_start_\name&_\key
	.popsection

        // Make an entry in the patch table.
	.pushsection .data.patch_table_\name
	// Bundle that will be moved to _patch_code_start, then replaced
	// with a jump to that location.
	.quad   .L_patch_insert_at_\name&_\key
	// Where the inserted code is located.
	.quad   _patch_code_start_\name&_\key
	// Patch mode.
	.hword  PATCH_MODE_INSERT_AFTER
	// End of entry.
	.align  8
	.popsection

        // Get rid of the temporary macro which called us.
        .purgem patch_end

	.endm

#endif /* __DOXYGEN__ */

#endif /* __ASSEMBLER__ */

#endif /* _SYS_HV_TILEGX_PATCH_H */
