// Copyright 2014 Tilera Corporation. All Rights Reserved.
//
//   The source code contained or described herein and all documents
//   related to the source code ("Material") are owned by Tilera
//   Corporation or its suppliers or licensors.  Title to the Material
//   remains with Tilera Corporation or its suppliers and licensors.
//   The software is licensed under the Tilera MDE License.
//
//   However, Licensee may elect to use this file under the terms of the
//   GNU Lesser General Public License version 2.1 as published by the
//   Free Software Foundation and appearing in the file src/COPYING.LIB
//   in the MDE distribution.  Please review the following information to
//   ensure the GNU Lesser General Public License version 2.1 requirements
//   will be met: http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html.

//! @file
//!
//! Support for user-level IPI event handling.
//!

#ifndef __TMC_IPI_H__
#define __TMC_IPI_H__

#include <features.h>
#include <tmc/cpus.h>

__BEGIN_DECLS

//! @addtogroup tmc_ipi
//! @{
//!
//! Routines for handling IPI events.
//!
//! Events generated by Interprocessor Interrupt (IPI), such as those
//! generated by IO shims, can be handled at user level through the use
//! of the support functions documented here.  These functions will allow
//! access to the IPI from user level, and allow the installation of a
//! callback function to handle IPI events.  The callback function will
//! be called from user level without an OS context switch.
//!
//! One handler may be installed for each IPI event on a particular
//! CPU.  Each CPU that handles an IPI event must activate the IPI
//! functionality and install the handler for each event the CPU
//! handles.  Different CPUs may install different handlers for the same
//! event.
//!
//! By default, the IPI mechanism assumes every CPU in the current
//! task's affinity set will be using the IPI mechanism.  To provide
//! a specific list of participating application CPUs, you must specify
//! a cpumask that includes all the CPUs that will be participating.
//! Either way, you must ensure that none of the CPUs that will be in the
//! set are part of another IPI hardwall group.  For a threaded application
//! you may simply initialize with the desired cpumask, then bind the
//! threads to run on particular CPUs before activing them.  For
//! a multi-process application, you should initialize in the parent
//! process, then fork the children.  See the <tmc/udn.h> header for
//! more details of how to set up hardwalls on UDN, which is similar
//! in spirit to setting up IPI groups.
//!
//! When a CPU designates another CPU as a target to handle events
//! from a shim, the target CPU must activate the IPI and install an
//! event handler.
//!
//! Installing an IPI event handler will result in the installation of a
//! user-level interrupt handler.  Only one user-level interrupt handler
//! may be installed per interrupt, and that interrupt must be handled
//! at user-level system-wide. Therefore if any CPU uses an IPI event
//! handler, no CPU may install a different handler for the IPI interrupt.


//! Initialize the IPI functionality for this process.
//!
//! In a multi-threaded process, tmc_ipi_init() uses locking to ensure
//! that two threads can not invoke it at the same time.  In general, the
//! initial parent thread should call tmc_ipi_init() before any other
//! threads are created; if not, each thread should individually
//! ensure that it calls tmc_ipi_init() prior to installing an IPI event
//! handler.  A thread should not assume that some other thread's call to
//! tmc_ipi_init() happens early enough to allow the first thread to
//! invoke tmc_ipi functions.
//!
//! @return -1 (setting errno) on error, 1 (setting errno to EINVAL)
//! if already initialized properly, or zero.
//!
extern int
tmc_ipi_init(cpu_set_t* cpus);

//! Activate the IPI functionality on this CPU.  This function must be
//! called after tmc_ipi_init(), and before the event handler is installed
//! by tmc_ipi_event_install().
//!
//! @return -1 (setting errno) on error, or zero.
//!
extern int 
tmc_ipi_activate(void);

//! Deactivate the IPI functionality on this CPU.
//!
//! @return -1 (setting errno) on error, or zero.
//!
extern int 
tmc_ipi_deactivate(void);

//! The number of IPI events.
#define TMC_IPI_NUM_EVENTS 32

//! The maximum value for an IPI event.
#define TMC_IPI_MAX_EVENT (TMC_IPI_NUM_EVENTS - 1)

//! tmc_ipi_func_t is the user-space C callback function.
//!
//! @param arg Value specified at event registration time to pass to
//!   completion handler.
//!
typedef void (*tmc_ipi_func_t)(void* arg);

//! Function to install a C callback entry for an IPI event in user space.
//! The IPI capability must be initialized and activated before this function
//! is called.
//!
//! There are restrictions on the event handler function just as there are for
//! any interrupt handler.  For example, the handler may not hold a lock, and
//! it may not call printf.
//!
//! @param ipi IPI number to register.  May specify any appropriate IPI
//!   number for BME applications; must be 0 for userspace programs running
//!   under Linux.
//! @param event IPI event within IPI number to register.  Must be in the
//!   range 0 to TMC_IPI_MAX_EVENT.
//! @param func User-space C callback function to bind to the interrupt.
//! @param arg Value to be passed to the completion handler at event-handling
//!   time.
//! @return 0 on success, -1 on failure (and sets errno), 1 if this function
//! has been called before and an event handler is already installed.
//!
int tmc_ipi_event_install(int ipi, int event, tmc_ipi_func_t func, void* arg);

//! Function to allocate a particular IPI event.
//!
//! @param ipi IPI number to register.  May specify any appropriate IPI
//!   number for BME applications; must be 0 for userspace programs running
//!   under Linux.
//! @param event IPI event within IPI number to try to allocate.  Must be in
//!   the range 0 to TMC_IPI_MAX_EVENT.
//! @return -1 (setting errno) on error, allocated event number on success.
//!
int tmc_ipi_event_alloc(int ipi, int event);

//! Function to allocate an IPI event, if one is available.
//!
//! @param ipi IPI number to register.  May specify any appropriate IPI
//!   number for BME applications; must be 0 for userspace programs running
//!   under Linux.
//! @return -1 (setting errno) on error, allocated event number on success.
//!
int tmc_ipi_event_alloc_first_available(int ipi);

//! Function to deallocate a particular IPI event.
//!
//! @param ipi IPI number to register.  May specify any appropriate IPI
//!   number for BME applications; must be 0 for userspace programs running
//!   under Linux.
//! @param event IPI event within IPI number to deallocate.  Must be in
//!   the range 0 to TMC_IPI_MAX_EVENT.  Event must have previously
//!   been allocated.
//! @return -1 (setting errno) on error, 0 on success.
//!
int tmc_ipi_event_dealloc(int ipi, int event);

__END_DECLS

//! @}

#endif // __TMC_IPI_H__
