#!/usr/bin/env python
#
# Copyright 2014 Tilera Corporation. All Rights Reserved.
#
#   The source code contained or described herein and all documents
#   related to the source code ("Material") are owned by Tilera
#   Corporation or its suppliers or licensors.  Title to the Material
#   remains with Tilera Corporation or its suppliers and licensors. The
#   software is licensed under the Tilera MDE License.
#
#   Unless otherwise agreed by Tilera in writing, you may not remove or
#   alter this notice or any other notice embedded in Materials by Tilera
#   or Tilera's suppliers or licensors in any way.
#
# Create trace wrappers for system calls, based on an input header file.
#
# usage: mktrace <input.h >output.c
#
# This script expects its input file to contain pretty much just function
# prototypes.  Preprocessor commands and //-comments are ignored; most /*
# ... */ comments are not, and will confuse things.  Since preprocessor
# commands are ignored, definitions which depend on them are a bad idea.
# Types other than simple type names and pointers to them (like arrays,
# or pointers to functions) will also confuse things.
#
# Parameters may be followed by an optional printf format within /* .. */
# comments, which determines how they'll be printed in the trace; if this
# is omitted, we pick a default format based on the type.  The list of
# these defaults is found in the definition of fmts[] below, and can be
# augmented there if necessary.
#

import sys
import re

funcpat = re.compile(r"(.*)\s+(\w+)\s*\((.*)\)\s*;")

#
# Define type -> printf format translation
#
fmts = {}
fmts["int"] = "%d"
fmts["int*"] = "%p"
fmts["unsigned long"] = "%lu"
fmts["unsigned int"] = "%u"
fmts["unsigned long*"] = "%p"
fmts["time_t"] = "%ld"
fmts["void*"] = "%p"
fmts["const void*"] = "%p"
fmts["char*"] = "%p"
fmts["char**"] = "%p"
fmts["const char*"] = "%p"
fmts["time_t*"] = "%p"
fmts["loff_t*"] = "%p"
fmts["size_t"] = "%zd"
fmts["off_t"] = "%ld"
fmts["loff_t"] = "%lld"
fmts["long long*"] = "%p"
fmts["VirtualAddress"] = "%#lx"
fmts["uint32_t"] = "%u"
fmts["int32_t"] = "%d"


#
# Translate a type into a printf format
#
def type2fmt(type):
    if type in fmts:
        return fmts[type]
    else:
        # Pointer to struct foo defaults to %p
        if type.startswith("struct") and type.endswith("*"):
            return "%p"
        else:
            return None


#
# Process a declaration
#
def process(decl):
    #
    # First make sure that any asterisks aren't stuck to the name they're
    # declaring, and regularize the spacing; to make dealing with the
    # asterisks easier, we turn /* ... */ into # @< ... >@ first
    #
    decl = decl.strip()
    decl = decl.replace("/*", "@<")
    decl = decl.replace("*/", ">@")
    decl = decl.replace("*", " * ")
    decl = " ".join(decl.split())
    decl = decl.replace(" *", "*")

    #
    # Extract the major parts of the declaration
    #
    mat = funcpat.match(decl)
    if not mat:
        sys.stderr.write("mktrace.py: declaration in incorrect " \
            "format: %s\n" % decl)
        sys.exit(1)

    (type, name, argstr) = mat.groups()
    shortname = name.replace("sys_", "")
    fmt = type2fmt(type)

    #
    # Turn the arguments into a list of (type, name, format) tuples
    #
    args = []
    if argstr.strip() != "void":
        for a in argstr.split(","):
            if not a:
                continue
            f = None
            a = a.strip()
            if a.endswith(">@"):
                a = a[:-2]
                (a, f) = a.rsplit("@<", 1)
            (t, n) = a.rsplit(None, 1)

            if not f:
                f = type2fmt(t)
                if not f:
                    sys.stderr.write("mktrace.py: " \
                        "unknown type %s in %s\n" % \
                        (t, name))
                    sys.exit(1)

            args.append((t.strip(), n.strip(), f.strip()))

    #
    # Compute various comma-separated strings we'll use in a minute
    #
    argfmts = ", ".join([f for (t, n, f) in args])
    argnames = ", ".join([n for (t, n, f) in args])
    if argnames:
        argnamestrailcomma = argnames + ", "
    else:
        argnamestrailcomma = argnames
    argtypesnames = ", ".join([t + " " + n for (t, n, f) in args])

    #
    # Write out the actual trace function definition
    #
    print
    print type
    print name + "_trace(" + argtypesnames + ")"
    print "{"
    print " ", type, "retval =", name + "(" + argnames + ");"

    print '  SYSCALL_TRACE("%s(%s) = %s\\n", %sretval);' % (shortname,
        argfmts, fmt, argnamestrailcomma)
    print "  return retval;"
    print "}"


#
# Main program
#
def main(argv):
    print "// This file is automatically generated by mktrace.py;", \
        "DO NOT EDIT."
    print
    print '#include "debug.h"'
    print '#include "syscall.h"'
    print
    print "#ifdef DEBUG"

    decl = ""
    for i in sys.stdin:
        # Slurp in lines, ignoring preprocessor directives and
        # single-line comments; when we see a );, assume that's
        # the end of a declaration, and process whatever we've
        # accumulated.
        i = i.strip()
        if i.startswith("#") or i.startswith("//"):
            continue
        decl = decl + " " + i
        if i.find(");") != -1:
            process(decl)
            decl = ""

    print
    print "#endif /* DEBUG */"

if __name__ == "__main__":
    main(sys.argv)
