// Copyright 2014 Tilera Corporation. All Rights Reserved.
//
//   The source code contained or described herein and all documents
//   related to the source code ("Material") are owned by Tilera
//   Corporation or its suppliers or licensors.  Title to the Material
//   remains with Tilera Corporation or its suppliers and licensors. The
//   software is licensed under the Tilera MDE License.
//
//   Unless otherwise agreed by Tilera in writing, you may not remove or
//   alter this notice or any other notice embedded in Materials by Tilera
//   or Tilera's suppliers or licensors in any way.
//

// Get the base MMIO address for a shim.
code = 0x8000, read, nouser
int get_mmio_base(HV_PTE* base);

// Validate an offset and size to be added to the MMIO base in a PTE.
code = 0x8001, nouser
int check_mmio_offset(ulong offset, ulong size);
